config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'
  get 'persons/profile', as: 'user_root'
  resources :messes
  resources :menus
  post 'messes/new'
  devise_scope :user do
    authenticated :user do
      root 'persons#profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/active_menu.rb
class ActiveMenu < ActiveRecord::Base
  has_one :user
  has_one :week_menu
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :ingredients_counts
  has_many :messes, through: :ingredients_counts
end

app/models/ingredients_count.rb
class IngredientsCount < ActiveRecord::Base
  belongs_to :mess
  belongs_to :ingredient
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :week_menu
  belongs_to :mess

  scope :order_by_week_day, -> { order(week_day: :ASC) }
  scope :order_by_position, -> { order(position: :ASC) }
end

app/models/mess.rb
class Mess < ActiveRecord::Base
  has_many :ingredients_counts
  has_many :menus
  has_many :ingredients, through: :ingredients_counts
  accepts_nested_attributes_for :ingredients_counts

  def nutrition_count type
    r = 0
    ingredients_counts.each do |i|
      (r += i.count * i.ingredient.send(type) / 100).to_f
    end
    r
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :active_menu
  has_many :week_menus
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable
end

app/models/week_menu.rb
class WeekMenu < ActiveRecord::Base
  has_many :menus, -> {order_by_week_day.order_by_position}
  belongs_to :user
  belongs_to :active_menu
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @user = current_user
    @week_menus = @user.week_menus
    @active_menu = @user.active_menu
  end
end

app/controllers/messes_controller.rb
class MessesController < ApplicationController
  def new
    @mess = Mess.new
    @ingredients = @mess.ingredients.build
    # @ingredients_counts = @messes.ingredients_counts.build
  end

  def show
    @mess = Mess.find(params[:id])
    render layout: false
  end

  def create
    Mess.create(mess_params)
    redirect_to action: 'new', controller: 'messes'
  end

  private

  def mess_params
    params.require(:mess).permit(:name,
                                   :description,
                                   :category,
                                   :cooking_time, ingredient_ids: [])
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
  def week_days(day)
    days = {1 => "Понедельник",
                  2 => "Вторник",
                  3 => "Среда",
                  4 => "Четверг",
                  5 => "Пятница",
                  6 => "Субота",
                  7 => "Воскресенье"
    }
    days[day]
  end

  def food_reception(food)
    receptions = {1 => "Первый прием пищи ",
                  2 => "Второй прием пищи",
                  3 => "Третий прием пищи ",
                  4 => "Четвертый прием пищи",
                  5 => "Пятый прием пищи",
                  6 => "Шстой прием пищи",
                  7 => "Седьмой прием пищи"
    }
    receptions[food]

  end
end

app/helpers/messes_helper.rb
module MessesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sns</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
</head>
<body>
<div id="wrap">
  <main>
    <header class="head">
      <div class="container">
        <div class="row">
          <a class="head-logo col-md-3 " href="/persons/profile">
            Sports Nutrition Service
          </a>
          <% if user_signed_in? %>
            <div class="dropdown col-md-3 col-md-offset-6 ">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle head-section ">
                <%= current_user.email %>
                <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
              </a>
              <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dLabel">
                <li>
                  <a tabindex="-1" href="#">
                    <%= link_to 'Отредактировать профиль', edit_user_registration_path, :method => :get %>
                  </a>
                </li>
                <li class="divider"></li>
                <li>
                  <a tabindex="-1" href="#">
                    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
                  </a>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <main>
      <div class="container">
      <%= yield %>
    </div>
    </main>
  </main>
</div>
<footer class="foot">
  <div class="container">
    <div class="row">
      <a class="foot-connectUs col-md-3" id="myBtn">
        Обратная связь
      </a>
      <div id="myModal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <div class="row">
            <form>
              <fieldset class="foot-form">
                <p class="col-md-12">Напишите нам письмо</p>
                <div class="form-group col-md-12">
                  <input type="text" id="name" name="name" class="form-control " placeholder="Name">
                </div>
                <div class="form-group col-md-12">
                  <input type="text" id="email" name="email" class="form-control" placeholder="Email">
                </div>
                <div class="form-group col-md-12">
                  <textarea rows="3" id="description" name="description" class="form-control" placeholder="Description"></textarea>
                </div>
                <button type="submit" class="btn btn-warning pull-right">Отправить</button>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<div class="modal fade" tabindex="-1" id="mess-modal" role="dialog" aria-hidden="true">
<div class="modal-dialog modal-md">
  <div class="modal-content">
  </div>
</div>
</div>

</body>
</html>

app/views/menus/index.html.erb
<div class="row">
  <div class="menu-btn-add-new col-md-2 btn btn-success">
     Добавить новое меню
  </div>
  <%- @position = "" %>
  <%- @week_menus.each do |week_menu| %>
    <div class="col-md-12 menu-wrapp">
      <div class="col-md-12 ">
        <div class="menu-name col-md-9">
          <%= week_menu.name %>
          <%- if week_menu.id == @active_menu.id %>
            <span class="glyphicon glyphicon-ok-circle menu-active-icon" aria-hidden="true"></span>
            <span class="menu-active-icon">
              Активно
           </span>
            <% end %>
        </div>
        <div class="dropdown menu-wrapp-burger-btn col-md-1 col-md-offset-2 ">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle head-section ">
            <span class="glyphicon glyphicon-menu-hamburger menu-burger-btn" aria-hidden="true"></span>
          </a>
          <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dLabel">
            <li>
              <a tabindex="-1" href="#">
                <%= link_to 'Сделать активным' %>
              </a>
            </li>
            <li>
              <a tabindex="-1" href="#">
                <%= link_to 'Редактировать' %>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a tabindex="-1" href="#">
                <%= link_to 'Удалить' %>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-12 menu-description">
        <%- week_menu.menus.group_by(&:week_day).each do |day, menu| %>
          <div class="menu-day col-md-12">
            <div class="col-md-12 menu-day-wrapp">
              <div class="menu-day-name">
                <%= week_days(day) %>
              </div>
              <%- menu.each do |m| %>
                <%- if !(m.position == @position) %>
                  <div class="col-md-12 menu-reception">
                    <%= food_reception(m.position) %>
                  </div>
                <% end %>
                <%- @position = m.position %>
                <%= link_to m.mess.name, mess_path(m.mess), class: 'col-md-12 menu-mess-name' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <nav class="menu-pagination" aria-label="Page navigation">
    <ul class="pagination">
      <li>
        <a href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <li><a href="#">1</a></li>
      <li><a href="#">2</a></li>
      <li><a href="#">3</a></li>
      <li><a href="#">4</a></li>
      <li><a href="#">5</a></li>
      <li>
        <a href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
</div>

app/views/messes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 mess-form">
      <div class="panel-group">
        <div class="panel panel-success">
          <div class="mess-form-title panel-heading">Напишите рецепт блюда</div>
          <div class="panel-body">
            <%= form_for @mess do |mess_form| %>
              <div class="form-group col-md-12">
                <%= mess_form.label :name, for: "name", value: "Название" %>
                <%= mess_form.text_field :name, id: "name", class: "form-control mess-form" %>
              </div>
              <div class="form-group col-md-12">
                <%= mess_form.label :description, for: "description", value: "Рецепт приготовления" %>
                <%= mess_form.text_area :description, id: "description", class: "form-control mess-form-textarea mess-form" %>
              </div>
              <div class="form-group col-md-12">
                <%= mess_form.label :category, for: "category", value: "Категория блюда(первое, второе)" %>
                <%= mess_form.select :category, id: "category", class: "form-control mess-form" do %>
                  <% [['Первое', 1], ['Второе', 2]].each do |c| -%>
                    <%= content_tag(:option, c.first, value: c.last) %>
                  <% end %>
                <% end %>
              </div>
              <div class="form-group col-md-12">
                <%= mess_form.label :cooking_time, for: "time", value: "Время приготовления(мин)" %>
                <%= mess_form.number_field :cooking_time, id: "time", class: "form-control mess-form", value: "" %>
              </div>
              <div class="form-group col-md-12" id="myModal">
                <%= mess_form.label :ingredients, for: "mess-ingredient_ids", value: "Ингредиенты для приготовления" %><br/>
                <%= mess_form.select("ingredient_ids",
                                     Ingredient.all.collect {|i| [i.name, i.id]},
                                     {:include_hidden => false},
                                     {:multiple => true,
                                      :size => 5,
                                      :class => "js-example-basic-multiple form-control mess-form"}
                    )%>
              </div>
              <br/>
              <div class="col-md-12">
                <%= mess_form.submit "Добавить", class: "btn btn-success" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messes/show.html.erb
<div class="row">
  <div class="panel panel-success mess-modal-panel">
    <div class="panel-heading ">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <%= @mess.name %>
    </div>
    <div class="panel-body mess-modal-body">
      <div class="col-md-12 mess-modal-description">
        <%= @mess.description %>
      </div>
      <div class="mess-modal-ingredients col-md-12">
        Ингредиенты :
      </div><br />
        <%- @mess.ingredients.each do |i| %>
          <div class="col-md-12">
            <div class="mess-modal-ingredient ">
              <%= i.name %>
            </div><br />

          </div>
        <% end %>
      <div class="mess-modal-nutritional-value col-md-3">
        Белки : <%= @mess.nutrition_count('protein') %>
      </div>
      <div class="mess-modal-nutritional-value col-md-3">
        Жиры : <%= @mess.nutrition_count('fat') %>
      </div>
      <div class="mess-modal-nutritional-value col-md-3">
        Углеводы : <%= @mess.nutrition_count('carbs') %>
      </div>
      <div class="mess-modal-nutritional-value col-md-3">
        Калории : <%= @mess.nutrition_count('calories') %>
      </div>
      <div class="col-md-12 mess-modal-time">
        Время приготовления <%= @mess.cooking_time %> мин.
      </div>
    </div>
  </div>
</div>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>
<div class="col-md-12">
  <%= link_to 'Создать блюдо', new_mess_path, :method => :get %>
</div>
<div class="col-md-12">
  <%= link_to 'Создать menu', menus_path, :method => :get %>
</div>